#!/usr/bin/env node
// Build script to bundle spice-html5 into a single file

import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const spiceDir = 'public/spice-html5';

// Files must be loaded in this specific order (dependencies)
const files = [
  'spicearraybuffer.js',
  'enums.js',
  'atKeynames.js',
  'utils.js',
  'png.js',
  'lz.js',
  'quic.js',
  'bitmap.js',
  'spicedataview.js',
  'spicetype.js',
  'spicemsg.js',
  'wire.js',
  'spiceconn.js',
  'display.js',
  'port.js',
  'main.js',
  'inputs.js',
  'webm.js',
  'playback.js',
  'simulatecursor.js',
  'filexfer.js',
  'cursor.js',
  'ticket.js',
  'resize.js',
];

let bundle = `// spice-html5 bundle - auto-generated
// SPICE protocol implementation for HTML5/JavaScript
// License: LGPL-3.0
// This file is auto-generated by build-spice.mjs

(function(window) {
"use strict";

`;

for (const file of files) {
  const filepath = join(spiceDir, file);
  try {
    let content = readFileSync(filepath, 'utf-8');
    // Remove "use strict" since we have it at the top
    content = content.replace(/^"use strict";\s*/gm, '');
    bundle += `// === ${file} ===\n`;
    bundle += content;
    bundle += '\n\n';
  } catch (e) {
    console.warn(`Warning: Could not read ${file}: ${e.message}`);
  }
}

// Export SpiceMainConn to window
bundle += `
// Export to window for use in modules
window.SpiceMainConn = SpiceMainConn;

})(window);
`;

const outputPath = 'public/spice-bundle.js';
writeFileSync(outputPath, bundle);
console.log(`SPICE bundle created at ${outputPath} (${(bundle.length / 1024).toFixed(1)} KB)`);
